version: "3.7"

services:
  frontend:
    build:
      context: ./frontend/MioBook
    ports:
      - "5173:5173"
    environment:
      - BACKEND_HOST=localhost:8080
      - PORT=5173


  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/miobook
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD_FILE=./secrets/db_password.txt
    secrets:
      - db_password
    depends_on:
      - db


  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=./secrets/db_password.txt
      - MYSQL_DATABASE=miobook
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_password


volumes:
  db_data:

secrets:
  db_password:
    file: ./secrets/db_password.txt